### ISSUE TITLE
avocado/avocado-vt params bug

### ISSUE THREAD

**Issue by will-Do** [avocado-framework/avocado-vt#1004]
Hi @apahim @ldoktor 
Now we got avocado(36lts) crashed after merge https://github.com/avocado-framework/avocado-vt/pull/1002
```
Traceback (most recent call last):

  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado/avocado/core/job.py", line 519, in _run
    self.args.test_result_total)

  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado/avocado/core/runner.py", line 468, in run_suite
    summary, deadline)

  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado/avocado/core/runner.py", line 306, in run_test
    test_status.wait_for_early_status(proc, 10)

  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado/avocado/core/runner.py", line 116, in wait_for_early_status
    raise exceptions.TestError("Process died before it pushed "

TestError: Process died before it pushed early test_status.
```
```
Traceback (most recent call last):                                                                                                                                    
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap  
    self.run()                                                                     
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run         
    self._target(*self._args, **self._kwargs)                                      
  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado/avocado/core/runner.py", line 241, in _run_test
    early_state = instance.get_state()                                             
  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado-vt/avocado_vt/test.py", line 168, in get_state
    state["params"] = self.avocado_params                                          
  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado-vt/avocado_vt/test.py", line 139, in avocado_params
    return super(VirtTest, self).params                                            
AttributeError: 'super' object has no attribute 'params'                           
```
which turn out there's a hidden bug of moving ```self.params``` to ```self.avocado_params```
```
 @property
    def params(self):
        """
        Avocado-vt test params
        During `avocado.Test.__init__` this reports the original params but
        once the Avocado-vt params are set it reports those instead. This
        is necessary to complete the `avocado.Test.__init__` phase
        """
        try:
            return self.__params
        except AttributeError:
            return self.avocado_params
    @params.setter                                                                                                                                                    
    def params(self, value):                                                    
        """                                                                     
        For compatibility with 36lts we need to support setter on params        
        """                                                                     
        self.__params = value   

    @property                                                                     
    def avocado_params(self):                                                     
        """                                                                       
        Original Avocado (multiplexer/varianter) params                           
        """                                                                       
        return super(VirtTest, self).params
```
If not use avocado 36lts, after https://github.com/avocado-framework/avocado/commit/99af507926d92e1da25806125a5825374ecaf069 , we may not got the previous crash bug, but it still messed up ```params``` and ```avocado_params```

**Comment by ldoktor** [comment]
Oh, sorry about not checking the 36lts, we ought to include a functional test.... Never mind a hot fix is:

```patch
diff --git a/avocado_vt/test.py b/avocado_vt/test.py
index df557e4..0540119 100644
--- a/avocado_vt/test.py
+++ b/avocado_vt/test.py
@@ -103,6 +103,10 @@ class VirtTest(test.Test):
         self.tmpdir = os.path.dirname(self.workdir)
         # Move self.params to self.avocado_params and initialize virttest
         # (cartesian_config) params
+        try:
+            self.__avocado_params = self.__params
+        except AttributeError:
+            pass
         self.__params = utils_params.Params(vt_params)
         self.debugdir = self.logdir
         self.resultsdir = self.logdir
@@ -136,7 +140,10 @@ class VirtTest(test.Test):
         """
         Original Avocado (multiplexer/varianter) params
         """
-        return super(VirtTest, self).params
+        try:
+            return self.__avocado_params
+        except AttributeError:
+            return super(VirtTest, self).params
 
     @property
     def datadir(self):
```

but I'll go through it once again and polish it a bit...

**Comment by ldoktor** [comment]
The cleaner fix is here: https://github.com/avocado-framework/avocado-vt/pull/1005

**Comment by ldoktor** [comment]
The fix was applied, feel free to re-open if it still does not work for you... Thank you for spotting this, I'm working on a functional selftest to avoid such issues...

**Comment by will-Do** [comment]
Thanks @ldoktor
