### ISSUE TITLE
Continously cleanup iscsi env by setup_or_cleanup_iscsi will fail

### ISSUE THREAD

**Issue by qiankehan** [avocado-framework/avocado-vt#1008]
Execute following code:  
```py
#!/usr/bin/env python2
from virttest.utils_test.libvirt import setup_or_cleanup_iscsi

block_name = ['a', 'b', 'c']
for i in block_name:
    setup_or_cleanup_iscsi(is_setup=True, emulated_image=i)

for i in block_name:
    setup_or_cleanup_iscsi(is_setup=False, emulated_image=i)
```
The result:  
> \# python /tmp/setup.py                                                                                                                    
Traceback (most recent call last):
  File "/tmp/setup.py", line 9, in <module>
    setup_or_cleanup_iscsi(is_setup=False, emulated_image=i)
  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado-vt/virttest/utils_test/libvirt.py", line 531, in setup_or_cleanup_iscsi
    _iscsi.cleanup()
  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado-vt/virttest/iscsi.py", line 342, in cleanup
    self.logout()
  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado-vt/virttest/iscsi.py", line 336, in logout
    iscsi_logout(self.target)
  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado-vt/virttest/iscsi.py", line 146, in iscsi_logout
    output = process.system_output(cmd)
  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado/avocado/utils/process.py", line 1124, in system_output
    sudo=sudo)
  File "/var/lib/libvirt_ci/runtest_avocado-vt/avocado/avocado/utils/process.py", line 1031, in run
    raise CmdError(cmd, sp.result)
avocado.utils.process.CmdError: Command 'iscsiadm --mode node --logout -T iqn.2017-05.com.virttest:c.target' failed (rc=9)

**Comment by xutian** [comment]
man iscsiadm found rc=9   is   ISCSI_ERR_INTERNAL, see details in below
EXIT STATUS
       On success 0 is returned. On error one of the return codes below will be returned.

       Commands  that  operation  on  multiple  objects  (sessions, records, etc), iscsiadm/iscsistart will return the first error that is encountered.  iscsi-
       adm/iscsistart will attempt to execute the operation on the objects it can. If no objects are found ISCSI_ERR_NO_OBJS_FOUND is returned.
....

       9      ISCSI_ERR_INTERNAL - generic internal iscsid/kernel failure.

I suggest you upgrade iscsid in you host, then have a try.
