### ISSUE TITLE
vt-bootstrap won't run anymore if interrupted once during git-clone

### ISSUE THREAD

**Issue by ehabkost** [avocado-framework/avocado-vt#126]
When I try to run vt-bootstrap, I see this:

    $ ./scripts/avocado vt-bootstrap --vt-type qemu
    15:31:40 INFO | qemu test config helper
    15:31:40 INFO |
    15:31:40 INFO | 1 - Updating all test providers
    Traceback (most recent call last):
      File "./scripts/avocado", line 31, in <module>
        sys.exit(app.run())
      File "/home/ehabkost/rh/proj/virt/avocado/avocado/core/app.py", line 64, in run
        return self.parser.take_action()
      File "/home/ehabkost/rh/proj/virt/avocado/avocado/core/parser.py", line 103, in take_action
        return self.args.dispatch(self.args)
      File "/home/ehabkost/rh/proj/virt/avocado/avocado/core/plugins/vt_bootstrap.py", line 105, in run
        bootstrap.bootstrap(options=args, interactive=True)
      File "/home/ehabkost/rh/proj/virt/avocado/virttest/bootstrap.py", line 732, in bootstrap
        asset.download_all_test_providers(options.vt_update_providers)
      File "/home/ehabkost/rh/proj/virt/avocado/virttest/asset.py", line 330, in download_all_test_providers
        download_test_provider(provider, update)
      File "/home/ehabkost/rh/proj/virt/avocado/virttest/asset.py", line 321, in download_test_provider
        process.system('git log -1')
      File "/home/ehabkost/rh/proj/virt/avocado/avocado/utils/process.py", line 989, in system
        allow_output_check=allow_output_check, shell=shell, env=env)
      File "/home/ehabkost/rh/proj/virt/avocado/avocado/utils/process.py", line 949, in run
        raise CmdError(cmd, sp.result)
    avocado.utils.process.CmdError: Command 'git log -1' failed (rc=128)
    $

I have no idea why this is happening:
* I don't know where vt-bootstrap is trying to run git-log
* Error output doesn't include git-log stderr, so I don't know why git-log is failing

I know I have interrupted vt-bootstrap while it was running, a few minutes ago, but I have made my git clones clean again by running `git reset --hard` and `git clean -dfx` (see `git status` output below). I don't know where Avocado could be storing any additional state.

Full log:

    $ pwd
    /home/ehabkost/rh/proj/virt/avocado
    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working directory clean
    $ git log -1
    commit e6771b88eb84f85cea45434acc3fc0057bc7374f
    Merge: 7044cc0 43d64f2
    Author: Cleber Rosa <crosa@redhat.com>
    Date:   Mon Sep 14 02:45:43 2015 -0300
    
        Merge remote-tracking branch 'haoliu/zip_safe'
    $ cd ../avocado-vt
    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working directory clean
    $ git log -1
    commit a7d1ae8efdb7cfc548837a7108fc94ee7300f8fc
    Merge: e54c0ba 7144e82
    Author: Lucas Meneghel Rodrigues <lmr@redhat.com>
    Date:   Fri Sep 11 11:59:18 2015 -0300
    
        Merge pull request #113 from will-Do/missing_param_fix
    
        ovirt: Fix the missing param bug
    $ make link
    ln -sf ../../../../avocado-vt/etc/avocado/conf.d/vt.conf ../avocado/etc/avocado/conf.d/
    ln -sf ../../../../avocado-vt/avocado/core/plugins/vt.py ../avocado/avocado/core/plugins/
    ln -sf ../../../../avocado-vt/avocado/core/plugins/vt_list.py ../avocado/avocado/core/plugins/
    ln -sf ../../../../avocado-vt/avocado/core/plugins/vt_bootstrap.py ../avocado/avocado/core/plugins/
    ln -sf ../avocado-vt/virttest ../avocado/
    $ cd ../avocado
    $ ./scripts/avocado vt-bootstrap --vt-type qemu
    15:31:40 INFO | qemu test config helper
    15:31:40 INFO |
    15:31:40 INFO | 1 - Updating all test providers
    Traceback (most recent call last):
      File "./scripts/avocado", line 31, in <module>
        sys.exit(app.run())
      File "/home/ehabkost/rh/proj/virt/avocado/avocado/core/app.py", line 64, in run
        return self.parser.take_action()
      File "/home/ehabkost/rh/proj/virt/avocado/avocado/core/parser.py", line 103, in take_action
        return self.args.dispatch(self.args)
      File "/home/ehabkost/rh/proj/virt/avocado/avocado/core/plugins/vt_bootstrap.py", line 105, in run
        bootstrap.bootstrap(options=args, interactive=True)
      File "/home/ehabkost/rh/proj/virt/avocado/virttest/bootstrap.py", line 732, in bootstrap
        asset.download_all_test_providers(options.vt_update_providers)
      File "/home/ehabkost/rh/proj/virt/avocado/virttest/asset.py", line 330, in download_all_test_providers
        download_test_provider(provider, update)
      File "/home/ehabkost/rh/proj/virt/avocado/virttest/asset.py", line 321, in download_test_provider
        process.system('git log -1')
      File "/home/ehabkost/rh/proj/virt/avocado/avocado/utils/process.py", line 989, in system
        allow_output_check=allow_output_check, shell=shell, env=env)
      File "/home/ehabkost/rh/proj/virt/avocado/avocado/utils/process.py", line 949, in run
        raise CmdError(cmd, sp.result)
    avocado.utils.process.CmdError: Command 'git log -1' failed (rc=128)
    $

**Comment by ehabkost** [comment]
Found the root cause:

    $ pwd
    /home/ehabkost/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-libvirt
    $ git log
    fatal: bad default revision 'HEAD'
    $ 

The problems are:
* It seem to be very easy to get into this broken state by simply interrupting `vt-bootstrap` while it is cloning repositories.
* The error message doesn't have any info about the broken repository location, and has no `git log -1` error output.
* README.rst mentions that some symlinks are created, but I had no idea that a `~/avocado` dir was going to be created.

**Comment by lmr** [comment]
Sure, those are all fair concerns. The ~/avocado dir is the default location for the base directory, where one stores data files, such as isos, and also the the persisted test results. Maybe we could be more explicit about the ~/avocado dir, although we did try to explain it in the read the docs documentation.

As for getting into a broken state, I think we can better handle git commands failing by trying to reset/re-download the test provider directories.

**Comment by ehabkost** [comment]
I will open a separate issue for README.rst "Getting Started" suggestions (including one about mentioning `~/avocado`), and keep this issue open for tracking the "vt-bootstrap breaks if interrupted during git-clone" issue.

**Comment by adereis** [comment]
Happened to me as well: I hit Ctrl+C during the early stages of vt-bootstrap and ended up with a broken setup. After removing ~/avocado/data/avocado-vt, I could start the bootstrap process again.

**Comment by lmr** [comment]
This has been addressed in #164.

**Comment by lmr** [comment]
Closing due to #164 merge.
