### ISSUE TITLE
backup file rename possible problem

### ISSUE THREAD

**Issue by svirt** [avocado-framework/avocado-vt#144]
Helllo,

seems there is a problem while backup/restoring images while running with libvirt

ran:
```
avocado run unattended_install.import.import.default_install.aio_native remove_guest.without_disk --vt-type libvirt --show-job-log
```

traceback:
```
# added print "src, exist, _dst, exists, dst, exists"

Checking image file /usr/share/avocado/data/avocado-vt/images/jeos-21-64.qcow2
Copying /usr/share/avocado/data/avocado-vt/images/jeos-21-64.qcow2.backup -> /usr/share/avocado/data/avocado-vt/images/jeos-21-64.qcow2
/usr/share/avocado/data/avocado-vt/images/jeos-21-64.qcow2.backup True /usr/share/avocado/data/avocado-vt/images/jeos-21-64.qcow2.part True /usr/share/avocado/data/avocado-vt/images/jeos-21-64.qcow2 True
Encoding video file /root/avocado/job-results/job-2015-09-17T15.11-97030cd/test-results/io-github-autotest-qemu.unattended_install.import.import.default_install.aio_native/screendumps_avocado-vt-vm1_11820_iter0.webm
/usr/share/avocado/data/avocado-vt/images/jeos-21-64.qcow2.backup True /usr/share/avocado/data/avocado-vt/images/jeos-21-64.qcow2.part False /usr/share/avocado/data/avocado-vt/images/jeos-21-64.qcow2 True

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/plugins/vt.py:566
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/avocado/core/plugins/vt.py", line 352, in runTest
    self._runTest()
  File "/usr/lib/python2.7/site-packages/avocado/core/plugins/vt.py", line 510, in _runTest
    env_process.postprocess(self, params, env)
  File "/usr/lib/python2.7/site-packages/virttest/error_context.py", line 135, in new_fn
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/virttest/env_process.py", line 858, in postprocess
    process(test, params, env, postprocess_image, postprocess_vm, vm_first=True)
  File "/usr/lib/python2.7/site-packages/virttest/env_process.py", line 543, in process
    _call_image_func()
  File "/usr/lib/python2.7/site-packages/virttest/env_process.py", line 530, in _call_image_func
    vm_process_status)
  File "/usr/lib/python2.7/site-packages/virttest/env_process.py", line 435, in process_images
    vm_process_status=vm_process_status)
  File "/usr/lib/python2.7/site-packages/virttest/env_process.py", line 452, in _process_images_serial
    image_func(test, image_params, image_name, vm_process_status)
  File "/usr/lib/python2.7/site-packages/virttest/env_process.py", line 327, in postprocess_image
    image.backup_image(params, base_dir, "restore", True)
  File "/usr/lib/python2.7/site-packages/virttest/storage.py", line 418, in backup_image
    backup_func(src, dst)
  File "/usr/lib/python2.7/site-packages/virttest/storage.py", line 333, in backup_image_file
    os.rename(_dst, dst)
OSError: [Errno 2] No such file or directory

Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/avocado/core/plugins/vt.py", line 608, in _run_avocado
    raise test_exception

OSError: [Errno 2] No such file or directory

ERROR io-github-autotest-libvirt.remove_guest.without_disk -> OSError: [Errno 2] No such file or directory
```

**Comment by ldoktor** [comment]
@svirt thanks, I'm on it...

**Comment by svirt** [comment]
@ldoktor: Thanks. we already were discussiing it together today
