### ISSUE TITLE
avocado vt-bootstrap on a venv

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado-vt#2193]
Needs to be addressed:

```
...
2 - Checking the recommended programs
/usr/bin/qemu-kvm OK
/usr/bin/qemu-img OK
/usr/bin/qemu-io OK

  - 3 - Updating test providers repo configuration from local copy
Avocado crashed unexpectedly: cannot copy tree '/tmp/venv/lib/python3.7/site-packages/test-providers.d': not a directory
```

**Comment by eskultety** [comment]
Can you describe the steps that lead to this problem? I'm not able to reproduce this issue in my testing.

**Comment by clebergnu** [comment]
@eskultety have you run this as a privileged or non-privileged user?

**Comment by clebergnu** [comment]
@eskultety never mind, I'm now also unable to reproduce it... I should have kept a better list of reproducible steps.

**Comment by clebergnu** [comment]
I've hit this issue again.

**Comment by eskultety** [comment]
> I've hit this issue again.

Do you have reproducer this time?

**Comment by clebergnu** [comment]
Yes, I do:

```
#!/bin/sh -x -e
VENVDIR=$(mktemp -d)
python3 -m venv $VENVDIR
source $VENVDIR/bin/activate
pip install avocado-framework==71.0
pip install avocado-framework-plugins-vt==71.0
avocado vt-bootstrap --vt-skip-verify-download-assets --yes-to-all
```

Output is:

```
bash -x /tmp/reproduce.sh 
+ '[' -z '' ']'
+ case "$-" in
+ __lmod_vx=x
+ '[' -n x ']'
+ set +x
Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for this output (/usr/share/lmod/lmod/init/bash)
Shell debugging restarted
+ unset __lmod_vx
++ mktemp -d
+ VENVDIR=/tmp/tmp.obktQAhBBK
+ python3 -m venv /tmp/tmp.obktQAhBBK
+ source /tmp/tmp.obktQAhBBK/bin/activate
++ deactivate nondestructive
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n /usr/bin/bash -o -n '' ']'
++ hash -r
++ '[' -n '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/tmp/tmp.obktQAhBBK
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/home/cleber/.local/bin:/usr/libexec/python2-sphinx:/home/cleber/.local/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
++ PATH=/tmp/tmp.obktQAhBBK/bin:/home/cleber/.local/bin:/usr/libexec/python2-sphinx:/home/cleber/.local/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
++ export PATH
++ '[' -n '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' 'x(tmp.obktQAhBBK) ' '!=' x ']'
++ PS1='(tmp.obktQAhBBK) '
++ export PS1
++ '[' -n /usr/bin/bash -o -n '' ']'
++ hash -r
+ pip install avocado-framework==71.0
Collecting avocado-framework==71.0
  Using cached https://files.pythonhosted.org/packages/ad/d5/2ed1e89fdb1334634de5a0df67b599db24f654508612ac793de5288ef279/avocado_framework-71.0-py3-none-any.whl
Requirement already satisfied: setuptools in /tmp/tmp.obktQAhBBK/lib/python3.7/site-packages (from avocado-framework==71.0) (40.8.0)
Installing collected packages: avocado-framework
Successfully installed avocado-framework-71.0
You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.                                                                        
+ pip install avocado-framework-plugins-vt==71.0
Collecting avocado-framework-plugins-vt==71.0
  Downloading https://files.pythonhosted.org/packages/89/7b/3860d5d1e6059463b2d0ea763e063fc5fb65a4238fb95ba5f4084b0b1343/avocado_framework_plugins_vt-71.0-py3-none-any.whl (8.0MB)
    100% |████████████████████████████████| 8.0MB 3.1MB/s 
Requirement already satisfied: avocado-framework>=68.0 in /tmp/tmp.obktQAhBBK/lib/python3.7/site-packages (from avocado-framework-plugins-vt==71.0) (71.0)
Collecting simplejson (from avocado-framework-plugins-vt==71.0)
  Using cached https://files.pythonhosted.org/packages/e3/24/c35fb1c1c315fc0fffe61ea00d3f88e85469004713dab488dee4f35b0aff/simplejson-3.16.0.tar.gz
Collecting six (from avocado-framework-plugins-vt==71.0)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting netaddr (from avocado-framework-plugins-vt==71.0)
  Using cached https://files.pythonhosted.org/packages/ba/97/ce14451a9fd7bdb5a397abf99b24a1a6bb7a1a440b019bebd2e9a0dbec74/netaddr-0.7.19-py2.py3-none-any.whl
Collecting netifaces (from avocado-framework-plugins-vt==71.0)
  Using cached https://files.pythonhosted.org/packages/0d/18/fd6e9c71a35b67a73160ec80a49da63d1eed2d2055054cc2995714949132/netifaces-0.10.9.tar.gz
Collecting aexpect (from avocado-framework-plugins-vt==71.0)
  Using cached https://files.pythonhosted.org/packages/6a/00/37aa80f16584bac6074fecca61607391feb976fc78674b3e6e7c5e6c8c14/aexpect-1.5.1-py3-none-any.whl
Requirement already satisfied: setuptools in /tmp/tmp.obktQAhBBK/lib/python3.7/site-packages (from avocado-framework>=68.0->avocado-framework-plugins-vt==71.0) (40.8.0)
Installing collected packages: simplejson, six, netaddr, netifaces, aexpect, avocado-framework-plugins-vt
  Running setup.py install for simplejson ... done
  Running setup.py install for netifaces ... done
Successfully installed aexpect-1.5.1 avocado-framework-plugins-vt-71.0 netaddr-0.7.19 netifaces-0.10.9 simplejson-3.16.0 six-1.12.0
You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.                                                                        
+ avocado vt-bootstrap --vt-skip-verify-download-assets --yes-to-all
Failed to load plugin from module "avocado_vt.plugins.vt": OSError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message") :                                                                                                                         
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/avocado/core/extension_manager.py", line 62, in __init__                                
    plugin = ep.load()                                                                                                                            
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load                                          
    return self.resolve()                                                                                                                         
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve                                       
    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                         
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/avocado_vt/plugins/vt.py", line 47, in <module>
    raise EnvironmentError("Bootstrap missing. "

Failed to load plugin from module "avocado_vt.plugins.vt_list": OSError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message") :
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/avocado/core/extension_manager.py", line 62, in __init__
    plugin = ep.load()
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/avocado_vt/plugins/vt_list.py", line 32, in <module>
    from .vt import add_basic_vt_options, add_qemu_bin_vt_option
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/avocado_vt/plugins/vt.py", line 47, in <module>
    raise EnvironmentError("Bootstrap missing. "

Running bootstrap for qemu

1 - Checking the mandatory programs and headers
/bin/xz OK
/sbin/tcpdump OK
/bin/nc OK
/sbin/ip OK
/sbin/arping OK
/bin/gcc OK
/usr/include/bits/socket.h OK
/usr/include/bits/types.h OK
/usr/include/bits/unistd.h OK
/usr/include/python3.7m/Python.h OK

2 - Checking the recommended programs
/bin/qemu-kvm OK
/bin/qemu-img OK
/bin/qemu-io OK

3 - Updating test providers repo configuration from local copy
Avocado crashed unexpectedly: cannot copy tree '/tmp/tmp.obktQAhBBK/lib/python3.7/site-packages/test-providers.d': not a directory
You can find details in /tmp/tmp.obktQAhBBK/data/crashes/avocado-traceback-2019-08-16_15:01:40-dohkli8i.log
```

And crash details:

```
Avocado crashed:
Traceback (most recent call last):
  File "/tmp/tmp.obktQAhBBK/bin/avocado", line 78, in <module>
    sys.exit(app.run())
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/avocado/core/app.py", line 91, in run
    return method(self.parser.config)
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/avocado_vt/plugins/vt_bootstrap.py", line 111, in run
    bootstrap.bootstrap(options=args, interactive=True)
  File "/tmp/tmp.obktQAhBBK/lib64/python3.7/site-packages/virttest/bootstrap.py", line 863, in bootstrap
    dir_util.copy_tree(tp_base_dir, tp_local_dir)
  File "/usr/lib64/python3.7/distutils/dir_util.py", line 124, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree '/tmp/tmp.obktQAhBBK/lib/python3.7/site-packages/test-providers.d': not a directory
```

**Comment by clebergnu** [comment]
I suspect @ldoktor came up with a fix (did not test yet):

https://github.com/avocado-framework/avocado-vt/pull/2203

**Comment by ldoktor** [comment]
Well I don't have a fix, just a workaround that works with `make install` without venv. As for the real fix we should rework the `virttest.datadir` to properly use the `pkg_resources` instead of the custom handling.

**Comment by ldoktor** [comment]
Actaully, looking at the symptoms the `--prefix` might actually fix this... So yes, @clebergnu, please re-test it with that patch and I guess it'll work well.

**Comment by clebergnu** [comment]
I'm hoping to get #2221 (or something like it) so that we can add the fixes *and* the coverage for the deployment in venvs. @eskultety @ldoktor you review is appreciated there.

**Comment by beraldoleal** [comment]
I'm also having this same issue here.

**Comment by ldoktor** [comment]
> I'm also having this same issue here.

hmm, shouldn't this have been resolved already? Can you elaborate a bit more? Are you going to work on this or do you want us to pursuit your issue?

**Comment by fanyang89** [comment]
The cause of this problem is getting a wrong ROOT_DIR in bootstrap.py.
virttest/data_dir.py:34
```
ROOT_DIR = os.path.abspath(_ROOT_PATH)
BASE_BACKEND_DIR = os.path.join(ROOT_DIR, 'backends')
DATA_DIR = os.path.join(data_dir.get_data_dir(), 'avocado-vt')
SHARED_DIR = os.path.join(ROOT_DIR, 'shared')
DEPS_DIR = os.path.join(ROOT_DIR, 'shared', 'deps')
BASE_DOWNLOAD_DIR = os.path.join(SHARED_DIR, 'downloads')
DOWNLOAD_DIR = os.path.join(DATA_DIR, 'downloads')
TEST_PROVIDERS_DIR = os.path.join(ROOT_DIR, 'test-providers.d')
BACKING_DATA_DIR = None
```

@clebergnu  Modify ROOT_DIR to yours, then run `avovado vt-bootstrap` again. 

You can insert

```
import pdb; pdb.set_trace()
```

after ROOT_DIR line, then input `p ROOT_DIR` to show it and check.
