### ISSUE TITLE
mac generator issue

### ISSUE THREAD

**Issue by bssrikanth** [avocado-framework/avocado-vt#2209]
Looks like newly integrated mac generator has a regression. I hit below scenario today.. noticing two issues:
1. generated mac is only 40 bits/5 octets instead of 6.
2. after discarding invalid mac, we seem to be generated newer mac by adding 1 to last octet of older mac without checking if old mac was wrong/right.

I was looking into this for a while now, thought of opening an issue here to get attention/advice from @luckyh 

```
2019-08-19 23:45:40,181 virt_vm          L0920 DEBUG| Generating random mac address for nic
2019-08-19 23:45:40,194 libvirt_vm       L1978 DEBUG| VM.create activating nic {'netdst': 'virbr0', 'ip': None, 'nic_name': 'nic1', 'mac': '52:54:00:be:e1', 'nettype': 'bridge', 'nic_model': 'virtio', 'g_nic_name': None}
2019-08-19 23:45:40,237 utils_net        L2682 WARNI| Discarded invalid mac "52:54:00:be:e1" for nic "nic1" from input, 10 warnings remaining.
2019-08-19 23:45:40,244 libvirt_vm       L0205 INFO | Libvirt VM 'vm1', driver 'qemu', uri 'qemu:///system'
2019-08-19 23:45:41,376 libvirt_vm       L0978 DEBUG| Machine types supported for hvm/ppc64le: ['pseries-rhel7.6.0', 'pseries', 'pseries-rhel7.6.0-sxxm', 'pseries-rhel7.3.0-sxxm', 'pseries-rhel7.5.0', 'pseries-rhel7.5.0-sxxm', 'pseries-rhel7.2.0', 'pseries-rhel7.4.0-sxxm', 'pseries-rhel7.3.0', 'pseries-rhel7.4.0']
2019-08-19 23:45:41,378 libvirt_vm       L0897 DEBUG| vm.add_memballoon returning:  --memballoon model=virtio
2019-08-19 23:45:41,379 virt_vm          L0920 DEBUG| Generating random mac address for nic
2019-08-19 23:45:41,410 libvirt_vm       L1299 DEBUG| make_create_command() setting up command for nic: {'netdst': 'virbr0', 'ip': None, 'nic_name': 'nic1', 'mac': '52:54:00:be:e2', 'nettype': 'bridge', 'nic_model': 'virtio', 'g_nic_name': None}
2019-08-19 23:45:41,411 libvirt_vm       L0881 DEBUG| vm.make_create_command.add_nic returning:  --network=bridge=virbr0,model=virtio,mac=52:54:00:be:e2
2019-08-19 23:45:41,411 libvirt_vm       L1984 INFO | Running libvirt command (reformatted):
2019-08-19 23:45:41,411 libvirt_vm       L1986 INFO | /usr/bin/virt-install
2019-08-19 23:45:41,411 libvirt_vm       L1986 INFO |     --connect=qemu:///system
2019-08-19 23:45:41,411 libvirt_vm       L1986 INFO |     --hvm
2019-08-19 23:45:41,412 libvirt_vm       L1986 INFO |     --accelerate
2019-08-19 23:45:41,412 libvirt_vm       L1986 INFO |     --name 'vm1'
2019-08-19 23:45:41,412 libvirt_vm       L1986 INFO |     --machine pseries
2019-08-19 23:45:41,412 libvirt_vm       L1986 INFO |     --memory=8096
2019-08-19 23:45:41,412 libvirt_vm       L1986 INFO |     --vcpu=4,cores=4
2019-08-19 23:45:41,412 libvirt_vm       L1986 INFO |     --import
2019-08-19 23:45:41,412 libvirt_vm       L1986 INFO |     --vnc
2019-08-19 23:45:41,412 libvirt_vm       L1986 INFO |     --os-variant centos7.0
2019-08-19 23:45:41,413 libvirt_vm       L1986 INFO |     --serial pty
2019-08-19 23:45:41,413 libvirt_vm       L1986 INFO |     --memballoon model=virtio
2019-08-19 23:45:41,413 libvirt_vm       L1986 INFO |     --disk path=/home/srikanth/avocado-fvt-wrapper/data/avocado-vt/images/rhel76alt-ppc64le_vm1.qcow2,bus=virtio,size=10,format=qcow2
2019-08-19 23:45:41,413 libvirt_vm       L1986 INFO |     --network=bridge=virbr0,model=virtio,mac=52:54:00:be:e2
2019-08-19 23:45:41,413 libvirt_vm       L1986 INFO |     --noautoconsole
2019-08-19 23:45:41,415 process          L0626 INFO | Running '/usr/bin/virt-install --connect=qemu:///system --hvm --accelerate --name 'vm1' --machine pseries --memory=8096 --vcpu=4,cores=4 --import --vnc --os-variant centos7.0 --serial pty --memballoon model=virtio --disk path=/home/srikanth/avocado-fvt-wrapper/data/avocado-vt/images/rhel76alt-ppc64le_vm1.qcow2,bus=virtio,size=10,format=qcow2 --network=bridge=virbr0,model=virtio,mac=52:54:00:be:e2 --noautoconsole'
2019-08-19 23:45:42,657 process          L0458 DEBUG| [stderr] ERROR    XML error: unable to parse mac address '52:54:00:be:e2'
2019-08-19 23:45:42,674 process          L0458 DEBUG| [stdout]
2019-08-19 23:45:42,675 process          L0458 DEBUG| [stdout] Starting install...
2019-08-19 23:45:42,676 process          L0458 DEBUG| [stderr] Domain installation does not appear to have been successful.
2019-08-19 23:45:42,676 process          L0458 DEBUG| [stderr] If it was, you can restart your domain by running:
2019-08-19 23:45:42,676 process          L0458 DEBUG| [stderr]   virsh --connect qemu:///system start vm1
2019-08-19 23:45:42,676 process          L0458 DEBUG| [stderr] otherwise, please restart your installation.
2019-08-19 23:45:42,717 process          L0714 INFO | Command '/usr/bin/virt-install --connect=qemu:///system --hvm --accelerate --name 'vm1' --machine pseries --memory=8096 --vcpu=4,cores=4 --import --vnc --os-variant centos7.0 --serial pty --memballoon model=virtio --disk path=/home/srikanth/avocado-fvt-wrapper/data/avocado-vt/images/rhel76alt-ppc64le_vm1.qcow2,bus=virtio,size=10,format=qcow2 --network=bridge=virbr0,model=virtio,mac=52:54:00:be:e2 --noautoconsole' finished with 1 after 1.29985189438s
2019-08-19 23:45:42,778 stacktrace       L0041 ERROR|
2019-08-19 23:45:42,778 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_plugins_vt-70.0-py2.7.egg/avocado_vt/test.py:449
2019-08-19 23:45:42,780 stacktrace       L0047 ERROR| Traceback (most recent call last):
2019-08-19 23:45:42,780 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-70.0-py2.7.egg/virttest/error_context.py", line 135, in new_fn
2019-08-19 23:45:42,780 stacktrace       L0047 ERROR|     return fn(*args, **kwargs)
2019-08-19 23:45:42,780 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-70.0-py2.7.egg/virttest/env_process.py", line 1116, in preprocess
2019-08-19 23:45:42,780 stacktrace       L0047 ERROR|     process(test, params, env, preprocess_image, preprocess_vm)
2019-08-19 23:45:42,780 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-70.0-py2.7.egg/virttest/env_process.py", line 709, in process
2019-08-19 23:45:42,781 stacktrace       L0047 ERROR|     _call_vm_func()
2019-08-19 23:45:42,781 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-70.0-py2.7.egg/virttest/env_process.py", line 648, in _call_vm_func
2019-08-19 23:45:42,781 stacktrace       L0047 ERROR|     vm_func(test, vm_params, env, vm_name)
2019-08-19 23:45:42,781 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-70.0-py2.7.egg/virttest/env_process.py", line 142, in preprocess_vm
2019-08-19 23:45:42,781 stacktrace       L0047 ERROR|     vm.create(params=params)
2019-08-19 23:45:42,781 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-70.0-py2.7.egg/virttest/error_context.py", line 135, in new_fn
2019-08-19 23:45:42,781 stacktrace       L0047 ERROR|     return fn(*args, **kwargs)
2019-08-19 23:45:42,781 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-70.0-py2.7.egg/virttest/libvirt_vm.py", line 1988, in create
2019-08-19 23:45:42,781 stacktrace       L0047 ERROR|     process.run(install_command, verbose=True, shell=True)
2019-08-19 23:45:42,782 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_framework-68.0-py2.7.egg/avocado/utils/process.py", line 1383, in run
2019-08-19 23:45:42,782 stacktrace       L0047 ERROR|     raise CmdError(cmd, sp.result)
2019-08-19 23:45:42,782 stacktrace       L0047 ERROR| CmdError: Command '/usr/bin/virt-install --connect=qemu:///system --hvm --accelerate --name 'vm1' --machine pseries --memory=8096 --vcpu=4,cores=4 --import --vnc --os-variant centos7.0 --serial pty --memballoon model=virtio --disk path=/home/srikanth/avocado-fvt-wrapper/data/avocado-vt/images/rhel76alt-ppc64le_vm1.qcow2,bus=virtio,size=10,format=qcow2 --network=bridge=virbr0,model=virtio,mac=52:54:00:be:e2 --noautoconsole' failed.
2019-08-19 23:45:42,782 stacktrace       L0047 ERROR| stdout: '\nStarting install...\n'
2019-08-19 23:45:42,782 stacktrace       L0047 ERROR| stderr: "ERROR    XML error: unable to parse mac address '52:54:00:be:e2'\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start vm1\notherwise, please restart your installation.\n"
2019-08-19 23:45:42,782 stacktrace       L0047 ERROR| additional_info: None
2019-08-19 23:45:42,782 stacktrace       L0048 ERROR|
2019-08-19 23:45:42,876 libvirt_vm       L2181 DEBUG| Releasing MAC addresses for vm vm1.
```

This issue is intermittent, not able to recreate for sometime now.

**Comment by bssrikanth** [comment]
thinking of looping at below until we get 6 octect
in utils_net.py
```
    @classmethod
    def complete_mac_address(cls, mac):
        """
        Append randomly generated byte strings to make mac complete

        :param mac: String or list of mac bytes (possibly incomplete)
        :raise: TypeError if mac is not a string or a list
        """
        mac = cls.mac_str_to_int_list(mac)
        nr_bytes = len(mac)
        assert not (nr_bytes > 6)
        while nr_bytes < 6:
            mac = cls._generate_eui48(mac)
            nr_bytes = len(mac)
```
could that be right solution?

**Comment by luckyh** [comment]
> thinking of looping at below until we get 6 octect
> in utils_net.py
> 
> ```
>     @classmethod
>     def complete_mac_address(cls, mac):
>         """
>         Append randomly generated byte strings to make mac complete
> 
>         :param mac: String or list of mac bytes (possibly incomplete)
>         :raise: TypeError if mac is not a string or a list
>         """
>         mac = cls.mac_str_to_int_list(mac)
>         nr_bytes = len(mac)
>         assert not (nr_bytes > 6)
>         while nr_bytes < 6:
>             mac = cls._generate_eui48(mac)
>             nr_bytes = len(mac)
> ```
> 
> could that be right solution?

well, I'm afraid not.

Would you please let me know how to trigger that issue? thanks.

**Comment by bssrikanth** [comment]
@luckyh there is no pattern to trigger it, I have hit that once till now, not able to recreate at will.

in the post above i had overridden original mac, which is getting passed to _generate_eui48.. that could be issue.. so would below do?

```    
@classmethod
    def complete_mac_address(cls, mac):
        """
        Append randomly generated byte strings to make mac complete

        :param mac: String or list of mac bytes (possibly incomplete)
        :raise: TypeError if mac is not a string or a list
        """
        mac = cls.mac_str_to_int_list(mac)
        nr_bytes = len(mac)
        assert not (nr_bytes > 6)
       if nr_bytes < 6:
            mac_tmp = mac
            while nr_bytes < 6:
                 mac = cls._generate_eui48(mac_tmp)
                 nr_bytes = len(mac)
        return ":".join(cls.int_list_to_mac_str(mac))
```

**Comment by luckyh** [comment]
@bssrikanth looks like the issue is caused by the following conversion:
https://github.com/avocado-framework/avocado-vt/blob/3f08daad420df4e1afce67638d1eebe99907e03d/virttest/utils_net.py#L2528-L2539

```python
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def int_to_int_list(number):
...     out = []
...     while number > 0:
...         out.insert(0, number & 0xff)
...         number >>= 8
...     if not out:
...         out.append(0)
...     return out
... 
>>> int_to_int_list(0x001234567800)
[18, 52, 86, 120, 0]
```

that is if the mac addr has the `0x00` octet in its high order bytes, the method would give a wrong result.

Will work on a fix, thank you for reporting the issue!

**Comment by bssrikanth** [comment]
Thanks @luckyh

**Comment by bssrikanth** [comment]
Tested the proposed patch. Mac generator now works fine returning 6 octets. Thanks @luckyh

**Comment by luckyh** [comment]
@bssrikanth thank you, too.
