### ISSUE TITLE
Qemu: Parameter 'bus' is unexpected

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado-vt#2414]
Running with avocado > 72.0 and using the now default `qemu_force_use_drive_expression=no` results in the following error when creating the qemu vm:

```
2020-01-29 20:32:38,586 qemu_vm          L2852 DEBUG| Buses of mis1
  drive_cd1(QDrive): {}
  drive_image1(QDrive): {drive:image1}
  isdnhub.0(uhci): {1:usb-tablet1}
  floppy(floppy): [None,None]
  ide(ide): [drive_cd1,None,None,None]
  vcpu_bus(EPYC): {}
  _PCI_CHASSIS_NR(None): {}
  _PCI_CHASSIS(None): {}
  pci.0(PCI): {0x0-0x0:t'i440FX',0x1-0x0:t'PIIX3',0x1-0x1:t'piix3-ide',0x1-0x3:t'PIIX4_PM',0x2-0x0:a'VGA',0x3-0x0:isdnhub,0x4-0x0:image1,0x5-0x0:idDYM4Jj,0x6-0x0:idE2JyDt,0x7-0x0:idjGPCHZ}
2020-01-29 20:32:38,587 qemu_vm          L2923 INFO | Running qemu command (reformatted):
/usr/bin/qemu-kvm \
    -S  \
    -name 'mis1' \
    -machine pc  \
    -nodefaults \
    -device VGA,bus=pci.0,addr=0x2 \
    -m 1024  \
    -smp 2,maxcpus=2,cores=1,threads=1,dies=1,sockets=2  \
    -cpu 'EPYC'  \
    -chardev socket,id=hmp_id_hmp1,path=/tmp/monitor-hmp1-20200129-203237-v7PMAw63,server,nowait \
    -mon chardev=hmp_id_hmp1,mode=readline  \
    -chardev socket,id=hmp_id_catch_monitor,path=/tmp/monitor-catch_monitor-20200129-203237-v7PMAw63,server,nowait \
    -mon chardev=hmp_id_catch_monitor,mode=readline \
    -chardev socket,server,nowait,path=/tmp/serial-serial0-20200129-203237-v7PMAw63,id=chardev_serial0 \
    -device isa-serial,id=serial0,chardev=chardev_serial0  \
    -chardev socket,id=seabioslog_id_20200129-203237-v7PMAw63,path=/tmp/seabios-20200129-203237-v7PMAw63,server,nowait \
    -device isa-debugcon,chardev=seabioslog_id_20200129-203237-v7PMAw63,iobase=0x402 \
    -device piix3-usb-uhci,id=isdnhub,bus=pci.0,addr=0x3 \
    -blockdev node-name=file_image1,driver=file,filename=/mnt/local/images/c12_mis1/BusinessServer_64.qcow2,cache.direct=on,cache.no-flush=off \
    -blockdev node-name=drive_image1,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_image1 \
    -device virtio-blk-pci,id=image1,drive=drive_image1,write-cache=on,bus=pci.0,addr=0x4 \
    -device virtio-net-pci,mac=02:00:00:00:01:01,id=idDYM4Jj,netdev=idhf3qgt,bus=pci.0,addr=0x5  \
    -netdev tap,id=idhf3qgt,fd=25 \
    -device virtio-net-pci,mac=02:00:00:00:01:02,id=idE2JyDt,netdev=idgADhQt,bus=pci.0,addr=0x6  \
    -netdev tap,id=idgADhQt,fd=34 \
    -device virtio-net-pci,mac=02:00:00:00:01:03,id=idjGPCHZ,netdev=idGq4nXA,bus=pci.0,addr=0x7  \
    -netdev tap,id=idGq4nXA,fd=40 \
    -blockdev node-name=file_cd1,driver=file,read-only=on,filename=/mnt/local/isos/business-server-6-7-0.iso,cache.direct=on,cache.no-flush=off \
    -blockdev node-name=drive_cd1,driver=raw,read-only=on,cache.direct=on,cache.no-flush=off,file=file_cd1,bus=ide.0,unit=0 \
    -device usb-tablet,id=usb-tablet1,bus=isdnhub.0,port=1  \
    -vnc :0  \
    -rtc base=utc,clock=host  \
    -boot menu=off,order=cdn,once=dcn \
    -enable-kvm
2020-01-29 20:32:38,689 client           L0611 INFO | [qemu output] qemu-system-x86_64: -blockdev node-name=drive_cd1,driver=raw,read-only=on,cache.direct=on,cache.no-flush=off,file=file_cd1,bus=ide.0,unit=0: Parameter 'bus' is unexpected
2020-01-29 20:32:38,691 client           L0611 INFO | [qemu output] (Process terminated with status 1)
2020-01-29 20:32:38,756 qemu_vm          L2935 INFO | Created qemu process with parent PID 396337
2020-01-29 20:32:39,089 utils_net        L1187 DEBUG| Host does not support OpenVSwitch: Command 'ovs-vswitchd' could not be found in any of the PATH dirs: ['/bin', '/usr/libexec', '/usr/sbin', '/usr/local/sbin', '/usr/bin', '/sbin', '/usr/local/bin']
2020-01-29 20:32:39,101 utils_net        L1187 DEBUG| Host does not support OpenVSwitch: Command 'ovs-vswitchd' could not be found in any of the PATH dirs: ['/bin', '/usr/libexec', '/usr/sbin', '/usr/local/sbin', '/usr/bin', '/sbin', '/usr/local/bin']
2020-01-29 20:32:39,111 utils_net        L1187 DEBUG| Host does not support OpenVSwitch: Command 'ovs-vswitchd' could not be found in any of the PATH dirs: ['/bin', '/usr/libexec', '/usr/sbin', '/usr/local/sbin', '/usr/bin', '/sbin', '/usr/local/bin']
2020-01-29 20:32:39,128 stacktrace       L0039 ERROR| 
2020-01-29 20:32:39,128 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/lib/python3.7/site-packages/avocado_vt/test.py:436
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR|   File "/usr/lib/python3.7/site-packages/virttest/error_context.py", line 135, in new_fn
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR|     return fn(*args, **kwargs)
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR|   File "/usr/lib/python3.7/site-packages/virttest/env_process.py", line 1216, in preprocess
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR|     process(test, params, env, preprocess_image, preprocess_vm)
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR|   File "/usr/lib/python3.7/site-packages/virttest/env_process.py", line 758, in process
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR|     _call_vm_func()
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR|   File "/usr/lib/python3.7/site-packages/virttest/env_process.py", line 697, in _call_vm_func
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR|     vm_func(test, vm_params, env, vm_name)
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR|   File "/usr/lib/python3.7/site-packages/virttest/env_process.py", line 258, in preprocess_vm
2020-01-29 20:32:39,132 stacktrace       L0045 ERROR|     migration_exec_cmd=params.get("migration_exec_cmd_dst"))
2020-01-29 20:32:39,133 stacktrace       L0045 ERROR|   File "/usr/lib/python3.7/site-packages/virttest/error_context.py", line 135, in new_fn
2020-01-29 20:32:39,133 stacktrace       L0045 ERROR|     return fn(*args, **kwargs)
2020-01-29 20:32:39,133 stacktrace       L0045 ERROR|   File "/usr/lib/python3.7/site-packages/virttest/qemu_vm.py", line 2980, in create
2020-01-29 20:32:39,133 stacktrace       L0045 ERROR|     raise e
2020-01-29 20:32:39,133 stacktrace       L0045 ERROR| virttest.virt_vm.VMCreateError: VM creation command failed:    "/usr/bin/qemu-kvm -S  -name 'mis1' -machine pc  -nodefaults -device VGA,bus=pci.0,addr=0x2 -m 1024  -smp 2,maxcpus=2,cores=1,threads=1,dies=1,sockets=2  -cpu 'EPYC'  -chardev socket,id=hmp_id_hmp1,path=/tmp/monitor-hmp1-20200129-203237-v7PMAw63,server,nowait -mon chardev=hmp_id_hmp1,mode=readline  -chardev socket,id=hmp_id_catch_monitor,path=/tmp/monitor-catch_monitor-20200129-203237-v7PMAw63,server,nowait -mon chardev=hmp_id_catch_monitor,mode=readline -chardev socket,server,nowait,path=/tmp/serial-serial0-20200129-203237-v7PMAw63,id=chardev_serial0 -device isa-serial,id=serial0,chardev=chardev_serial0  -chardev socket,id=seabioslog_id_20200129-203237-v7PMAw63,path=/tmp/seabios-20200129-203237-v7PMAw63,server,nowait -device isa-debugcon,chardev=seabioslog_id_20200129-203237-v7PMAw63,iobase=0x402 -device piix3-usb-uhci,id=isdnhub,bus=pci.0,addr=0x3 -blockdev node-name=file_image1,driver=file,filename=/mnt/local/images/c12_mis1/BusinessServer_64.qcow2,cache.direct=on,cache.no-flush=off -blockdev node-name=drive_image1,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_image1 -device virtio-blk-pci,id=image1,drive=drive_image1,write-cache=on,bus=pci.0,addr=0x4 -device virtio-net-pci,mac=02:00:00:00:01:01,id=idDYM4Jj,netdev=idhf3qgt,bus=pci.0,addr=0x5  -netdev tap,id=idhf3qgt,fd=25 -device virtio-net-pci,mac=02:00:00:00:01:02,id=idE2JyDt,netdev=idgADhQt,bus=pci.0,addr=0x6  -netdev tap,id=idgADhQt,fd=34 -device virtio-net-pci,mac=02:00:00:00:01:03,id=idjGPCHZ,netdev=idGq4nXA,bus=pci.0,addr=0x7  -netdev tap,id=idGq4nXA,fd=40 -blockdev node-name=file_cd1,driver=file,read-only=on,filename=/mnt/local/isos/business-server-6-7-0.iso,cache.direct=on,cache.no-flush=off -blockdev node-name=drive_cd1,driver=raw,read-only=on,cache.direct=on,cache.no-flush=off,file=file_cd1,bus=ide.0,unit=0 -device usb-tablet,id=usb-tablet1,bus=isdnhub.0,port=1  -vnc :0  -rtc base=utc,clock=host  -boot menu=off,order=cdn,once=dcn -enable-kvm"    (status: 1,    output: "qemu-system-x86_64: -blockdev node-name=drive_cd1,driver=raw,read-only=on,cache.direct=on,cache.no-flush=off,file=file_cd1,bus=ide.0,unit=0: Parameter 'bus' is unexpected")
2020-01-29 20:32:39,133 stacktrace       L0046 ERROR| 
```

Has anyone seen this before?

**Comment by YongxueHong** [comment]
Could you provide the full log?
Thanks.

**Comment by YongxueHong** [comment]
Thanks, I will download it.

**Comment by pevogam** [comment]
I just retried `qemu_force_use_drive_expression=no` on top of Avocado VT 82.0 to see if something improved and get this error:
```
19:47:25 ERROR| Original Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/virttest/qemu_vm.py", line 2956, in create
    self.devices, self.spice_options = self.make_create_command()
  File "/usr/lib/python3.8/site-packages/virttest/qemu_vm.py", line 1946, in make_create_command
    devs = devices.images_define_by_params(image_name, image_params,
  File "/usr/lib/python3.8/site-packages/virttest/qemu_devices/qcontainer.py", line 2389, in images_define_by_params
    return self.images_define_by_variables(name,
  File "/usr/lib/python3.8/site-packages/virttest/qemu_devices/qcontainer.py", line 2025, in images_define_by_variables
    format_node = format_cls(name)
UnboundLocalError: local variable 'format_cls' referenced before assignment

19:47:25 ERROR| 
19:47:25 ERROR| Reproduced traceback from: /usr/lib/python3.8/site-packages/avocado_vt/test.py:442
19:47:25 ERROR| Traceback (most recent call last):
19:47:25 ERROR|   File "/usr/lib/python3.8/site-packages/virttest/qemu_vm.py", line 2956, in create
19:47:25 ERROR|     self.devices, self.spice_options = self.make_create_command()
19:47:25 ERROR|   File "/usr/lib/python3.8/site-packages/virttest/qemu_vm.py", line 1946, in make_create_command
19:47:25 ERROR|     devs = devices.images_define_by_params(image_name, image_params,
19:47:25 ERROR|   File "/usr/lib/python3.8/site-packages/virttest/qemu_devices/qcontainer.py", line 2389, in images_define_by_params
19:47:25 ERROR|     return self.images_define_by_variables(name,
19:47:25 ERROR|   File "/usr/lib/python3.8/site-packages/virttest/qemu_devices/qcontainer.py", line 2025, in images_define_by_variables
19:47:25 ERROR|     format_node = format_cls(name)
19:47:25 ERROR| UnboundLocalError: local variable 'format_cls' referenced before assignment
```
Just FYI.
