### ISSUE TITLE
Missing test assertion methods for the new VirtTest type

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado-vt#3221]
VT tests using previously provided assertion methods from the `avocado.core.test.Test` no longer work with errors like
```
[stderr] Traceback (most recent call last):
[stderr]   File "/usr/lib/python3.9/site-packages/avocado_vt/plugins/vt_runner.py", line 77, in run_test
[stderr]     self._run_test()
[stderr]   File "/usr/lib/python3.9/site-packages/avocado_vt/plugins/vt_runner.py", line 170, in _run_test
[stderr]     run_func(self, params, env)
[stderr]   File "/mnt/local/intra2net-qa/tp_i2n/tests/cyrus_list_mailboxes.py", line 169, in run
[stderr]     test_web_listing(test, vm)
[stderr]   File "/mnt/local/intra2net-qa/tp_i2n/tests/cyrus_list_mailboxes.py", line 136, in test_web_listing
[stderr]     test.assertCountEqual(output, expected_output)
[stderr] AttributeError: 'VirtTest' object has no attribute 'assertCountEqual'
```
The reason for this is that the `avocado_vt.plugins.vt_runner.VirtTest` does not inherit from `avocado.core.test.Test` which provides additional assertion methods all tests used to rely on.

A simple change like
```diff
diff --git a/avocado_vt/plugins/vt_runner.py b/avocado_vt/plugins/vt_runner.py
index 8b650344..b57a965f 100644
--- a/avocado_vt/plugins/vt_runner.py
+++ b/avocado_vt/plugins/vt_runner.py
@@ -6,7 +6,7 @@ import tempfile
 import time
 import traceback
 
-from avocado.core import exceptions, nrunner, output, teststatus
+from avocado.core import exceptions, nrunner, output, teststatus, test
 from avocado.core.runners.utils import messages
 from avocado.utils import stacktrace, path
 
@@ -15,7 +15,7 @@ from virttest import (data_dir, env_process, error_event, utils_env, utils_misc,
                       utils_params, version, funcatexit)
 
 
-class VirtTest(utils.TestUtils):
+class VirtTest(test.Test, utils.TestUtils):
 
     def __init__(self, queue, runnable):
         self.__vt_params = utils_params.Params(runnable.kwargs)
```
does not resolve the situation due to additional conflicts
```
[stderr] Traceback (most recent call last):
[stderr]   File "/usr/lib/python3.9/site-packages/avocado_vt/plugins/vt_runner.py", line 253, in run
[stderr]     vt_test = VirtTest(queue, self.runnable)
[stderr]   File "/usr/lib/python3.9/site-packages/avocado_vt/plugins/vt_runner.py", line 53, in __init__
[stderr]     self.logdir = os.path.join(self.tmpdir, 'results')
[stderr] AttributeError: can't set attribute
```

**Comment by pevogam** [comment]
@richtja Just in case you don't see this and want to share your opinion.

**Comment by richtja** [comment]
@pevogam thanks, for reporting this, me and @clebergnu already working on a solution.

**Comment by pevogam** [comment]
Solution is now acceptable.
