### ISSUE TITLE
avocado-vt travis Ci failed on python 3.6

### ISSUE THREAD

**Issue by chunfuwen** [avocado-framework/avocado-vt#3476]
one failed example is mentioned here [1] .
Some initial analysis follow as:
1)it create one folder to hold up avocado repository(/usr/bin/git config --global --add safe.directory /home/runner/work/avocado-vt/avocado-vt/avocado-libs)
2) then download repository: https://github.com/avocado-framework/avocado, and attempt to install by setup.py
3)error happen when install required packages[setuptools]
```
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-3bm2glrn/cryptography-37.0.4/setup.py", line 14, in <module>
        # Author: Cleber Rosa <crosa@redhat.com>
    ModuleNotFoundError: No module named 'setuptools_rust'
```

[1]https://github.com/avocado-framework/avocado-vt/runs/7578408324?check_suite_focus=true

**Comment by chunfuwen** [comment]
https://github.com/avocado-framework/avocado-vt/pull/3477/files

The fix may help fix this issue
