### ISSUE TITLE
Issue with popcan makes tests fail

### ISSUE THREAD

**Issue by smitterl** [avocado-framework/avocado-vt#3908]
On status 0c3a0a00484f5e633714d0e8bed6dddf0ff2828b
I see that the `marshal_from_address` cannot be found. This leads to follow-up issues of the VM not being in a correct state in the tp-libvirt tests libvirt_pci_passthrough.ism.
When I manually fix that, I yet again run into the same issue on another PCIXML object.
However, when I revert to the commit 394eaeb372c7576e6672670ce65a015c16c68b0e this doesn't happen.

**Comment by smitterl** [comment]
2024-05-09 10:41:34,104 stacktrace       L0041 ERROR| Reproduced traceback from: /var/ci/libvirt-ci/runtest/avocado-vt/avocado/avocado/core/test.py:793
2024-05-09 10:41:34,105 stacktrace       L0045 ERROR| Traceback (most recent call last):
2024-05-09 10:41:34,105 stacktrace       L0045 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/propcan.py", line 223, in __getattr__
2024-05-09 10:41:34,105 stacktrace       L0045 ERROR|     self.__canhaz__(key, KeyError)
2024-05-09 10:41:34,105 stacktrace       L0045 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/propcan.py", line 252, in __canhaz__
2024-05-09 10:41:34,105 stacktrace       L0045 ERROR|     raise excpt(
2024-05-09 10:41:34,105 stacktrace       L0045 ERROR| KeyError: "Key 'marshal_from_address' not found in super class attributes or in ('domain', 'bus', 'slot', 'function', 'product_id', 'vendor_id', 'virt_functions', 'numa_node', 'iommuGroup_number', 'iommuGroup_address', 'product_info', 'xml', 'virsh', 'xmltreefile', 'validates', 'xml', 'virsh', 'xmltreefile', 'validates', 'get_marshal_from_address', 'set_marshal_from_address', 'del_marshal_from_address')"

**Comment by smitterl** [comment]
2024-05-09 11:45:46,156 stacktrace       L0041 ERROR| Reproduced traceback from: /var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/avocado_vt/test.py:292
2024-05-09 11:45:46,157 stacktrace       L0045 ERROR| Traceback (most recent call last):
2024-05-09 11:45:46,157 stacktrace       L0045 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/propcan.py", line 223, in __getattr__
2024-05-09 11:45:46,157 stacktrace       L0045 ERROR|     self.__canhaz__(key, KeyError)
2024-05-09 11:45:46,157 stacktrace       L0045 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/propcan.py", line 252, in __canhaz__
2024-05-09 11:45:46,157 stacktrace       L0045 ERROR|     raise excpt(
2024-05-09 11:45:46,157 stacktrace       L0045 ERROR| KeyError: "Key 'marshal_from_address' not found in super class attributes or in ('domain', 'bus', 'slot', 'function', 'product_id', 'vendor_id', 'virt_functions', 'numa_node', 'iommuGroup_number', 'iommuGroup_address', 'product_info', 'xml', 'virsh', 'xmltreefile', 'validates', 'xml', 'virsh', 'xmltreefile', 'validates', 'get_marshal_from_address', 'set_marshal_from_address', 'del_marshal_from_address')"

**Comment by chloerh** [comment]
I have submitted https://github.com/avocado-framework/avocado-vt/pull/3909 to fix this issue, please help review, thanks.

**Comment by smitterl** [comment]
Thank you so much @chloerh !
