### ISSUE TITLE
Basic script failed by UnsupportedCPU.

### ISSUE THREAD

**Issue by kanssty** [avocado-framework/avocado-vt#505]
Hi,
I followed the guide of 
http://avocado-vt.readthedocs.io/en/latest/GetStartedGuide.html
to run a basic vt-scripts, but got the failed as below.

**UnsupportedCPU: CPU models reported by qemu -cpu ? not supported by avocado-vt. Please work with              us to add support for it**

What I did is as below.

[root@zs95kv2 avocado]# ./scripts/avocado run type_specific.io-github-autotest-qemu.migrate.default.tcp
JOB ID     : 72b2c57b2014a5034e11bc538271440069cf13bc
JOB LOG    : /root/avocado/job-results/job-2016-05-12T20.05-72b2c57/job.log
TESTS      : 1
 (1/1) type_specific.io-github-autotest-qemu.migrate.default.tcp: ERROR (0.35 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /root/avocado/job-results/job-2016-05-12T20.05-72b2c57/html/results.html
TIME       : 0.35 s
[root@zs95kv2 avocado]#

2016-05-12 20:02:08,330 stacktrace       L0036 ERROR|
2016-05-12 20:02:08,330 stacktrace       L0039 ERROR| Reproduced traceback from: /avocado/avocado-vt/avocado_vt/test.py:393
2016-05-12 20:02:08,332 stacktrace       L0042 ERROR| Traceback (most recent call last):
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|   File "/avocado/avocado-vt/avocado_vt/test.py", line 169, in runTest
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|     self._runTest()
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|   File "/avocado/avocado-vt/avocado_vt/test.py", line 301, in _runTest
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|     params = env_process.preprocess(self, params, env)
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|   File "/avocado/avocado-vt/virttest/error_context.py", line 135, in new_fn
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|     return fn(_args, *_kwargs)
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|   File "/avocado/avocado-vt/virttest/env_process.py", line 658, in preprocess
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|     env["cpu_model"] = utils_misc.get_qemu_best_cpu_model(params)
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|   File "/avocado/avocado-vt/virttest/utils_misc.py", line 2330, in get_qemu_best_cpu_model
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|     qemu_cpu_models = get_qemu_cpu_models(qemu_binary)
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|   File "/avocado/avocado-vt/virttest/utils_misc.py", line 2216, in get_qemu_cpu_models
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|     return extract_qemu_cpu_models(result.stdout)
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|   File "/avocado/avocado-vt/virttest/utils_misc.py", line 2206, in extract_qemu_cpu_models
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR|     raise UnsupportedCPU(e_msg)
2016-05-12 20:02:08,333 stacktrace       L0042 ERROR| UnsupportedCPU: CPU models reported by qemu -cpu ? not supported by avocado-vt. Please work with              us to add support for it
2016-05-12 20:02:08,333 stacktrace       L0043 ERROR|
2016-05-12 20:02:08,334 test             L0567 ERROR| ERROR 1-type_specific.io-github-autotest-qemu.migrate.default.tcp -> UnsupportedCPU: CPU models r             eported by qemu -cpu ? not supported by avocado-vt. Please work with us to add support for it
2016-05-12 20:02:08,334 test             L0554 INFO |
[root@zs95kv2 avocado]#

**Comment by kanssty** [comment]
Found another similar error message.
2016-05-12 20:18:38,755 utils_misc       L2088 DEBUG| Detected CPU vendor as 'IBM'
2016-05-12 20:18:38,755 utils_misc       L2169 WARNI| Can not Get cpu flags from cpuinfo
2016-05-12 20:18:38,798 utils_misc       L2203 ERROR| CPU models reported by qemu -cpu ? not supported by avocado-vt. Please work with us to add support for it
2016-05-12 20:18:38,798 utils_misc       L2205 ERROR| s390             host

**Comment by vmorris** [comment]
#509

**Comment by liwbj** [comment]
Done! After modify source code, it's OK now.

**Comment by vmorris** [comment]
@liwbj change from the #509 has been merged.

**Comment by xutian** [comment]
Pull request merged, let's close this issue. thanks @vmorris
