### ISSUE TITLE
Where is the shell and how to test and handle this error ?ShellCmdError: Shell command failed: 'sh -x  /tmp/copyfile.sh '

### ISSUE THREAD

**Issue by liwbj** [avocado-framework/avocado-vt#629]
2016-07-20 00:04:35,225 process          L0333 INFO | Running 'cd /usr/share/avocado-plugins-vt; \rm -f /tmp/copyfile.sh'
2016-07-20 00:04:35,253 stacktrace       L0038 ERROR|
2016-07-20 00:04:35,253 stacktrace       L0041 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_plugins_vt-38.0-py2.7.egg/avocado_vt/test.py:422
2016-07-20 00:04:35,254 stacktrace       L0044 ERROR| Traceback (most recent call last):
2016-07-20 00:04:35,254 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-38.0-py2.7.egg/avocado_vt/test.py", line 197, in runTest
2016-07-20 00:04:35,254 stacktrace       L0044 ERROR|     self._runTest()
2016-07-20 00:04:35,254 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-38.0-py2.7.egg/avocado_vt/test.py", line 339, in _runTest
2016-07-20 00:04:35,254 stacktrace       L0044 ERROR|     run_func(self, params, env)
2016-07-20 00:04:35,254 stacktrace       L0044 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/guest_test.py", line 78, in run
2016-07-20 00:04:35,254 stacktrace       L0044 ERROR|     session.cmd(cmd, print_func=logging.info, timeout=test_timeout)
2016-07-20 00:04:35,254 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/aexpect/client.py", line 1211, in cmd
2016-07-20 00:04:35,254 stacktrace       L0044 ERROR|     raise ShellCmdError(cmd, s, o)
2016-07-20 00:04:35,254 stacktrace       L0044 ERROR| ShellCmdError: Shell command failed: 'sh -x  /tmp/copyfile.sh '    (status: 1,    output: "+ dd if=/dev/zero of=/home/bigfile bs=1M count=2048\n2048+0 records in\n2048+0 records out\n2147483648 bytes (2.1 GB, 2.0 GiB) copied, 5.46042 s, 393 MB/s\n+ cp -f /home/{bigfile,bigfile.bak}\ncp: missing destination file operand after '/home/{bigfile,bigfile.bak}'\nTry 'cp --help' for more information.\n")
2016-07-20 00:04:35,254 stacktrace       L0045 ERROR|
2016-07-20 00:04:35,255 test             L0563 ERROR| Traceback (most recent call last):

2016-07-20 00:04:35,255 test             L0563 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-38.0-py2.7.egg/avocado_vt/test.py", line 436, in _run_avocado
    raise test_exception

2016-07-20 00:04:35,255 test             L0563 ERROR| ShellCmdError: Shell command failed: 'sh -x  /tmp/copyfile.sh '    (status: 1,    output: "+ dd if=/dev/zero of=/home/bigfile bs=1M count=2048\n2048+0 records in\n2048+0 records out\n2147483648 bytes (2.1 GB, 2.0 GiB) copied, 5.46042 s, 393 MB/s\n+ cp -f /home/{bigfile,bigfile.bak}\ncp: missing destination file operand after '/home/{bigfile,bigfile.bak}'\nTry 'cp --help' for more information.\n")

2016-07-20 00:04:35,255 test             L0580 ERROR| ERROR 1-qcow2.virtio_blk.smp2.virtio_net.Ubuntu.16.04-server.s390x.s390-virtio.io-github-autotest-qemu.guest_test.isa_serial_operations -> ShellCmdError: Shell command failed: 'sh -x  /tmp/copyfile.sh '    (status: 1,    output: "+ dd if=/dev/zero of=/home/bigfile bs=1M count=2048\n2048+0 records in\n2048+0 records out\n2147483648 bytes (2.1 GB, 2.0 GiB) copied, 5.46042 s, 393 MB/s\n+ cp -f /home/{bigfile,bigfile.bak}\ncp: missing destination file operand after '/home/{bigfile,bigfile.bak}'\nTry 'cp --help' for more information.\n")

**Comment by liwbj** [comment]
@lmr @clebergnu Any comments for this problem?
I am trying to find copyfile.sh, but I did not get it. Where does it come from and what content is it?

ShellCmdError: Shell command failed: 'sh -x /tmp/copyfile.sh ' (status: 1, output: "+ dd if=/dev/zero of=/home/bigfile bs=1M count=2048\n2048+0 records in\n2048+0 records out\n2147483648 bytes (2.1 GB, 2.0 GiB) copied, 5.46042 s, 393 MB/s\n+ cp -f /home/{bigfile,bigfile.bak}\ncp: missing destination file operand after '/home/{bigfile,bigfile.bak}'\nTry 'cp --help' for more information.\n
