### ISSUE TITLE
pre_command & post_command should be called no matter the result of a test.

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado-vt#881]
I have noticed that command from Cartesian config are not called for bad test:
pre_command = /xxxx
post_command = /yyyy

2017-02-09 16:07:27,625 stacktrace       L0036 ERROR| 
2017-02-09 16:07:27,626 stacktrace       L0039 ERROR| Reproduced traceback from: /mnt/tests/spice/qe-tests/virtualenv/src/avocado-plugins-vt/avocado_vt/test.py:420
2017-02-09 16:07:27,628 stacktrace       L0042 ERROR| Traceback (most recent call last):
2017-02-09 16:07:27,628 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/virtualenv/src/avocado-plugins-vt/avocado_vt/test.py", line 196, in runTest
2017-02-09 16:07:27,629 stacktrace       L0042 ERROR|     self._runTest()
2017-02-09 16:07:27,629 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/virtualenv/src/avocado-plugins-vt/avocado_vt/test.py", line 304, in _runTest
2017-02-09 16:07:27,630 stacktrace       L0042 ERROR|     test_modules[t_type] = imp.load_module(t_type, f, p, d)
2017-02-09 16:07:27,630 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice/spice/tests/rv_connect.py", line 19, in <module>
2017-02-09 16:07:27,631 stacktrace       L0042 ERROR|     from spice.lib import stest
2017-02-09 16:07:27,631 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice/spice/lib/__init__.py", line 19, in <module>
2017-02-09 16:07:27,632 stacktrace       L0042 ERROR|     from . import vm_actions
2017-02-09 16:07:27,632 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice/spice/lib/vm_actions.py", line 26, in <module>
2017-02-09 16:07:27,633 stacktrace       L0042 ERROR|     from spice.lib import reg
2017-02-09 16:07:27,633 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice/spice/lib/reg.py", line 41, in <module>
2017-02-09 16:07:27,633 stacktrace       L0042 ERROR|     from zope import interface
2017-02-09 16:07:27,634 stacktrace       L0042 ERROR| ImportError: No module named zope
2017-02-09 16:07:27,634 stacktrace       L0043 ERROR| 
2017-02-09 16:07:27,635 test             L0550 ERROR| Traceback (most recent call last):

2017-02-09 16:07:27,636 test             L0550 ERROR|   File "/mnt/tests/spice/qe-tests/virtualenv/src/avocado-plugins-vt/avocado_vt/test.py", line 434, in _run_avocado
    raise test_exception

2017-02-09 16:07:27,636 test             L0550 ERROR| ImportError: No module named zope

2017-02-09 16:07:27,637 test             L0567 ERROR| ERROR 1-cmdline_test.rv_connect.174366 -> ImportError: No module named zope
2017-02-09 16:07:27,637 test             L0554 INFO | 

pre_command / post_command are called from: avocado-plugins-vt/virttest/env_process.py

But, test has failed even before "pre_command" command.

My point that "pre_command / post_command"    should be called always. No matter what.

**Comment by Andrei-Stepanov** [comment]
SpiceQE team uses pre_command / post_command to notify beaker server about test results.
