### ISSUE TITLE
avocado exceptions seems broken for vt tests

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado-vt#934]
Looks like TestFail is reported as TestError

testcase:
virsh_unit.py:
```

from avocado.core import exceptions

def run(test, params, env):
    """
    Test command: result unit test
    """
    result_param = params.get("result_param")

    if 'skip' in result_param:
        raise exceptions.TestSkipError("Test Skip")
    elif 'pass' in result_param:
        logging.info("Test Pass")
        pass
    elif 'fail' in result_param:
        raise exceptions.TestFail("Test Fail")
    elif 'error' in result_param:
        raise exceptions.TestError("Test Error")
    else:
        pass
```

virsh_unit.cfg:
```

- virsh.unit:
    type = virsh_unit
    start_vm = no
    vms = ''
    main_vm = ''
    variants:
        - skip:
            result_param = 'skip'
        - pass:
            result_param = 'pass'
        - fail:
            result_param = 'fail'
        - error:
            result_param = 'error'
```

Result:
>  (1/4) guest_unit.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.25.ppc64le.powerkvm-libvirt.virsh.unit.skip: SKIP
>  (2/4) guest_unit.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.25.ppc64le.powerkvm-libvirt.virsh.unit.pass: PASS (1.64 s)
>  (3/4) guest_unit.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.25.ppc64le.powerkvm-libvirt.virsh.unit.fail: ERROR (1.62 s)---------NOK
>  (4/4) guest_unit.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.25.ppc64le.powerkvm-libvirt.virsh.unit.error: ERROR (1.51 s)
> RESULTS    : PASS 1 | ERROR 2 | FAIL 0 | SKIP 1 | WARN 0 | INTERRUPT 0 | CANCEL 0
> 

Avocado Commit used: bae2e3ad82fc400d080c8f3c11fc0bc7ca9cd704
Avocado-vt Commit used: 430aec4b51057e22ffcc41b222b2d112909af1b8

**Comment by sathnaga** [comment]
@ldoktor @clebergnu @apahim ^^

**Comment by xutian** [comment]
@sathnaga  can you show me your  job.log

**Comment by will-Do** [comment]
Recently we got a patch(37a315b8) merged in avocado-vt to run the test in setUp step, which resolved the TestSkipError problem, but a followed problem is that all other exceptions will be redirected to TestSetupFail( status= Error), that's the problem you see.
BTW, I just droped an mail to avocado-devel@ d days agos.

**Comment by sathnaga** [comment]
@will-Do Sure, looks like we are yet to hear back on the email-thread.

@xutian here is the part of log for failure case
```
2017-03-17 13:05:16,347 process          L0386 INFO | Running 'true'
2017-03-17 13:05:16,351 process          L0496 INFO | Command 'true' finished with 0 after 0.000565052032471s
2017-03-17 13:05:16,351 process          L0386 INFO | Running 'ps -o comm 1'
2017-03-17 13:05:16,461 process          L0476 DEBUG| [stdout] COMMAND
2017-03-17 13:05:16,461 process          L0496 INFO | Command 'ps -o comm 1' finished with 0 after 0.10617518425s
2017-03-17 13:05:16,462 process          L0476 DEBUG| [stdout] systemd
2017-03-17 13:05:16,544 qemu_storage     L0489 DEBUG| Checking image file /home/sath/runAvocadoFVTTest/avocado-fvt-wrapper/data/avocado-vt/images/f25-ppc64le.qcow2
2017-03-17 13:05:16,942 process          L0386 INFO | Running 'true'
2017-03-17 13:05:16,948 process          L0496 INFO | Command 'true' finished with 0 after 0.000616073608398s
2017-03-17 13:05:16,949 process          L0386 INFO | Running 'ps -o comm 1'
2017-03-17 13:05:17,059 process          L0476 DEBUG| [stdout] COMMAND
2017-03-17 13:05:17,059 process          L0496 INFO | Command 'ps -o comm 1' finished with 0 after 0.106781959534s
2017-03-17 13:05:17,059 process          L0476 DEBUG| [stdout] systemd
2017-03-17 13:05:17,499 stacktrace       L0038 ERROR| 
2017-03-17 13:05:17,500 stacktrace       L0041 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-47.0-py2.7.egg/avocado/core/test.py:578
2017-03-17 13:05:17,500 stacktrace       L0044 ERROR| Traceback (most recent call last):
2017-03-17 13:05:17,501 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-47.0-py2.7.egg/avocado_vt/test.py", line 225, in setUp
2017-03-17 13:05:17,501 stacktrace       L0044 ERROR|     self._runTest()
2017-03-17 13:05:17,501 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-47.0-py2.7.egg/avocado_vt/test.py", line 366, in _runTest
2017-03-17 13:05:17,501 stacktrace       L0044 ERROR|     run_func(self, params, env)
2017-03-17 13:05:17,501 stacktrace       L0044 ERROR|   File "/home/sath/runAvocadoFVTTest/avocado-fvt-wrapper/data/avocado-vt/test-providers.d/downloads/powerkvm-libvirt/libvirt/tests/src/virsh_cmd/domain/virsh_unit.py", line 15, in run
2017-03-17 13:05:17,501 stacktrace       L0044 ERROR|     raise exceptions.TestFail("Test Fail")
2017-03-17 13:05:17,502 stacktrace       L0044 ERROR| TestFail: Test Fail
2017-03-17 13:05:17,502 stacktrace       L0045 ERROR| 
2017-03-17 13:05:17,502 test             L0740 ERROR| ERROR 3-guest_unit.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.25.ppc64le.powerkvm-libvirt.virsh.unit.fail -> TestSetupFail: Test Fail

```

**Comment by ldoktor** [comment]
Hello guys, I'm sorry for causing this issue. I'll take a look at it later today. There were several changes and now I believe I'll be able to use `CANCEL` status for skips which will allow me to move things to `test` class again.

Once again, sorry for my fault, I only tested this change with `SKIP` tests and forgot about the rest.

**Comment by clebergnu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Define `avocado.core.test.Test` interface to make it easier to be subclassed](https://trello.com/c/WLI0qiFo/973-define-avocado-core-test-test-interface-to-make-it-easier-to-be-subclassed)
