### ISSUE TITLE
fail to login the serial console (new issue: custom guest don't work after updating avocado-vt)

### ISSUE THREAD

**Issue by 55504441** [avocado-framework/avocado-vt#983]
here is error log:
-----------
017-04-12 18:52:18,344 process          L0383 INFO | Running 'ps -o comm 1'
2017-04-12 18:52:18,360 process          L0473 DEBUG| [stdout] COMMAND
2017-04-12 18:52:18,360 process          L0493 INFO | Command 'ps -o comm 1' finished with 0 after 0.0122120380402s
2017-04-12 18:52:18,361 process          L0473 DEBUG| [stdout] systemd
2017-04-12 18:52:18,394 stacktrace       L0038 ERROR|
2017-04-12 18:52:18,394 stacktrace       L0041 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:571
2017-04-12 18:52:18,395 stacktrace       L0044 ERROR| Traceback (most recent call last):
2017-04-12 18:52:18,395 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_vt/test.py", line 225, in setUp
2017-04-12 18:52:18,395 stacktrace       L0044 ERROR|     self._runTest()
2017-04-12 18:52:18,395 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_vt/test.py", line 366, in _runTest
2017-04-12 18:52:18,395 stacktrace       L0044 ERROR|     run_func(self, params, env)
2017-04-12 18:52:18,395 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/autotest/client/shared/error.py", line 141, in new_fn
2017-04-12 18:52:18,395 stacktrace       L0044 ERROR|     return fn(*args, **kwargs)
2017-04-12 18:52:18,395 stacktrace       L0044 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/mq_change_qnum.py", line 109, i
n run
2017-04-12 18:52:18,396 stacktrace       L0044 ERROR|     session_serial = vm.wait_for_serial_login(timeout=login_timeout)
2017-04-12 18:52:18,396 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/virttest/virt_vm.py", line 1316, in wait_for_serial_login
2017-04-12 18:52:18,396 stacktrace       L0044 ERROR|     raise (exception or remote.LoginTimeoutError("timeout %ds" % timeout))
2017-04-12 18:52:18,396 stacktrace       L0044 ERROR| LoginTimeoutError: Login timeout expired    (output: '')
2017-04-12 18:52:18,396 stacktrace       L0045 ERROR|
---------------

**Comment by xutian** [comment]
can you try with latest avocado-vt ? it looks your code is old.

**Comment by 55504441** [comment]
hello xutian, 

thanks a lot for your quick reply,  could you please tell me how to update it to the  latest avocado-vt ? 
my current version is 47 as below:
#avocado --version
Avocado 47.0

**Comment by xutian** [comment]
git clone https://github.com/avocado-framework/avocado-vt.git
cd avocado-vt 
python setup.py install

then rerun your test.

**Comment by xutian** [comment]
if still failed, please provider full job.log.

**Comment by 55504441** [comment]
awesome,  I will try it tomorrow. thanks.

**Comment by 55504441** [comment]
after updating avocado-vt  according to your advice,  I meet a weird issue, that custom guest don't work.  my steps are below:
1. create a new guest like this:
cd /usr/share/avocado-plugins-vt/shared/cfg/guest-os/
 cp -r JeOS MyOS
2. reboot qemu:
 avocado vt-bootstrap --vt-type qemu
3. I can see my new guest as below:
# avocado list --vt-type qemu --vt-list-guests|grep -i my
Linux.MyOS.19.x86_64.i440fx (missing jeos-19-64.qcow2)
Linux.MyOS.20.x86_64.i440fx (missing jeos-20-64.qcow2)
Linux.MyOS.21.x86_64.i440fx (missing jeos-21-64.qcow2)
Linux.MyOS.22.x86_64.i440fx (missing jeos-22-64.qcow2)
Linux.MyOS.23.x86_64.i440fx (missing jeos-23-64.qcow2)
Linux.MyOS.25.x86_64.i440fx
4.  but avocado fail to support it as below, please tell me how to fix it? 
# avocado list -V Linux.MyOS.25.x86_64.i440fx
Type    Test
MISSING Linux.MyOS.25.x86_64.i440fx

ACCESS_DENIED: 0
BROKEN_SYMLINK: 0
EXTERNAL: 0
INSTRUMENTED: 0
MISSING: 1
NOT_A_TEST: 0
SIMPLE: 0
VT: 0

**Comment by 55504441** [comment]
further, JeOS is OK.
-----------
 avocado list -V Linux.JeOS.25.x86_64.i440fx
Type Test
VT   io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native
VT   io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads
VT   io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.perf.aio_native
VT   io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.perf.aio_threads
VT   io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.multi_disk_install.aio_native

**Comment by xutian** [comment]
I guess your step for add new guest OS is wrong, please verify with JeOS.

**Comment by 55504441** [comment]
fixed , thanks a lot
